# Specify version format
version: "{build}"

os: Visual Studio 2015

platform:
  - Win32

environment:
  BOOST_ROOT: C:\boost-release-master
  BOOST_LIBRARYDIR: C:\Libraries\boost\stage\lib
  BUILD_EXAMPLES: OFF  # don't build examples to not exceed allowed build time (40 min)

configuration:
  - Debug
  - Release
  
matrix:
  fast_finish: true
  
#----------------------------------------------------------------------------------------  
# lets go	
init:
  - cmd: cmake --version
  - cmd: msbuild /version  
  
install:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/ned14/boost-release/archive/master.zip', 'C:\master.zip')
  - ps: Add-Type -A System.IO.Compression.FileSystem
  - ps: "[IO.Compression.ZipFile]::ExtractToDirectory('C:\\master.zip', 'C:\\')"
  - cd "C:\boost-release-master"
  - bootstrap.bat --with-toolset=msvc-14.0
  - b2 --with-program_options --with-filesystem --with-system
  - cd "%APPVEYOR_BUILD_FOLDER%"
    - cmd: dir C:\boost-release-master
  
before_build:
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64
  - cmd: cd PackerPE
  - cmake . -B"build" -G"Visual Studio 14" -Wno-dev -DBOOST_ROOT="%BOOST_ROOT%" --debug-output -DBoost_DEBUG=ON
  
build:
  project: C:\projects\PackerPE\PackerPE\build\spack.sln # path to Visual Studio solution or project
  parallel: true                                         # enable MSBuild parallel builds
  verbosity: minimal                                     # MSBuild verbosity level (quiet|minimal|normal|detailed)